export const domain_names = {
  "m.et": ["m", 0],
  "m.cv": ["m", 0],
  "x.srl": ["m", 0],

  "mc.vc": ["m", 0],
  "mc.ke": ["m", 0],
  "mc.td": ["m", 0],
  "p8.pw": ["s", 0], 
  "8d.pw": ["s", 0], 
  "dn.onl": ["s", 0], 

  "uie.net": ["s", 0],
  "uck.net": ["s", 0],
  "m4x.net": ["s", 0],
  "m-c.net": ["m", 0],
  "f-c.net": ["s", 0],
  "azw.org": ["s", 0],
  "irs.biz": ["s", 0],
  "rpg.mobi": ["s", 0],

  "uie.xyz": ["s", 0],
  "tod.xyz": ["s", 0], 
  "orc.xyz": ["s", 0],
  "dab.xyz": ["s", 0],
  "ron.xyz": ["m", 0],
  "itm.xyz": ["s", 0],
  "2fa.xyz": ["s", 0], 

  "000002.xyz": ["m", 0], 
  "000006.xyz": ["m", 0], 
  "akimbo.xyz": ["m", 0], 
  "studious.xyz": ["m", 0], 

  "☚.com": ["m", 0],
  "i♥.com": ["m", 0],
  "☹.net": ["m", 0],
  "₥.com": ["m", 0],
  "€-bank.com": ["m", 0],
  "i♥u.com": ["m", 0],
  "₭.com": ["m", 0],
  "☴.com": ["s", 0],
  "com.kaufen": ["s", 0],
  "com.sarl": ["m", 0],
  "www.co.gg": ["m", 0],

  "prge.com": ["m", 0],
  "uxrn.com": ["m", 0],
  "urdn.com": ["m", 0],
  "mc-u.com": ["s", 0],
  "e2rs.com": ["s", 0],

  "arms.deal": ["m", 0],
  "armsdeal.com": ["m", 0],

  "dakimbo.com": ["m", 0],
  "akimbos.com": ["m", 0],
  "bettle.com": ["m", 0],
  "ebettle.com": ["m", 0],
  "deluxo.com": ["m", 0],
  "savies.com": ["s", 0], 
  "nregistry.com": ["m", 0],
  "montington.com": ["m", 0],

  "satisfy.org": ["s", 0],
  "geneve.org": ["s", 0],
  "molres.org": ["m", 0]
};
