export const domain_names = {
  "m.et": ["r", 0],
  "m.cv": ["r", 0],
  "x.srl": ["d", 0],
  "o.bo": ["r", 0],

  "mc.vc": ["r", 0],
  "mc.ke": ["r", 0],
  "mc.td": ["r", 0],
  "8d.pw": ["d", 0], 
  "np.gl": ["r", 0],
  "dn.onl": ["d", 0], 

  "uie.net": ["d", 0],
  "uck.net": ["d", 0],
  "m4x.net": ["d", 0],
  "m-c.net": ["d", 0],
  "f-c.net": ["d", 0],
  "azw.org": ["d", 0],
  "irs.biz": ["d", 0],
  "rpg.mobi": ["d", 0],
  "gfv.ai": ["d", 0],

  "uie.xyz": ["d", 0],
  "orc.xyz": ["d", 0],
  "dab.xyz": ["d", 0],
  "ron.xyz": ["d", 0],
  "itm.xyz": ["d", 0],
  "2fa.xyz": ["d", 0], 

  "000002.xyz": ["d", 0], 
  "000006.xyz": ["d", 0], 
  "333373.xyz": ["d", 0], 
  "222122.xyz": ["d", 0], 
  "898888.xyz": ["d", 0], 
  "989999.xyz": ["d", 0], 
  "akimbo.xyz": ["d", 0], 
  "studious.xyz": ["d", 0], 

  "☚.com": ["r", 0],
  "i♥.com": ["r", 0],
  "☹.net": ["r", 0],
  "₥.com": ["r", 0],
  "€-bank.com": ["r", 0],
  "i♥u.com": ["r", 0],
  "₭.com": ["r", 0],
  "☴.com": ["r", 0],
  
  "com.kaufen": ["d", 0],
  "com.sarl": ["d", 0],
  "www.co.gg": ["d", 0],

  "prge.com": ["d", 0],
  "uxrn.com": ["d", 0],
  "urdn.com": ["r", 0],
  "mc-u.com": ["d", 0],
  "e2rs.com": ["d", 0],

  "arms.deal": ["d", 0],
  "armsdeal.com": ["d", 0],

  "dakimbo.com": ["d", 0],
  "akimbos.com": ["d", 0],
  "bettle.com": ["d", 0],
  "ebettle.com": ["r", 0],
  "deluxo.com": ["r", 0],
  "savies.com": ["d", 0], 
  "montington.com": ["d", 0],

  "satisfy.org": ["d", 0],
  "geneve.org": ["d", 0],
  "molres.org": ["r", 0],

  "🤣.st": ["r", 0],
  "📧.st": ["r", 0],
  "🌐.st": ["r", 0],
  "👏.st": ["r", 0]
};
